Shape errors:
The inner dimensions must match. Like-----> [3, 2] and [2, 3] 

Multiplications cannot be executed if [a, b] and [a, b].

In [5]:
import numpy as np
import torch

a = torch.tensor([[1, 3], [4, 6]])
b = torch.tensor([[2, 7], [9, 1]])

c = torch.matmul(a, b)

c

tensor([[29, 10],
        [62, 34]])

In [4]:
x =  torch.tensor([[1, 5, 9],
                  [2, 7, 2],
                  [6, 9, 3]])
y = torch.tensor([[1, 3, 77],
                 [2, 5, 78]])

z = torch.matmul(x, y)

z

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x3)

To solve this issue we can use the **transpose** of the matrix. Using transpose method we can manipulate the **shape** of the matrix.


In [ ]:
Y = y.T

mulT = torch.matmul(x, Y)
mulT

tensor([[709, 729],
        [177, 195],
        [264, 291]])

Finding sum, mean, max etc using *rand* values

In [6]:
import numpy as np
arr1 = np.random.rand(7)
arr = torch.tensor(arr1)
print(torch.min(arr))
print(torch.max(arr))
print(torch.mean(arr))



tensor(0.3656, dtype=torch.float64)
tensor(0.9104, dtype=torch.float64)
tensor(0.5862, dtype=torch.float64)


Finding index of a min, max value in a tensor

In [7]:
print(arr.argmin())
print(arr.argmax())


tensor(4)
tensor(3)


Reshape

In [9]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [16]:
x_reshaped =x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [17]:
# change view
z = x.view(3, 3)
z, z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))