Shape errors:
The inner dimensions must match. Like-----> [3, 2] and [2, 3] 

Multiplications cannot be executed if [a, b] and [a, b].

In [35]:
import numpy as np
import torch

a = torch.tensor([[1, 3], [4, 6]])
b = torch.tensor([[2, 7], [9, 1]])

c = torch.matmul(a, b)

c

tensor([[29, 10],
        [62, 34]])

In [36]:
x =  torch.tensor([[1, 5, 9],
                  [2, 7, 2],
                  [6, 9, 3]])
y = torch.tensor([[1, 3, 77],
                 [2, 5, 78]])

z = torch.matmul(x, y)

z

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x3)

To solve this issue we can use the **transpose** of the matrix. Using transpose method we can manipulate the **shape** of the matrix.


In [ ]:
Y = y.T

mulT = torch.matmul(x, Y)
mulT

tensor([[709, 729],
        [177, 195],
        [264, 291]])

Finding sum, mean, max etc using *rand* values

In [ ]:
import numpy as np
arr1 = np.random.rand(7)
arr = torch.tensor(arr1)
print(torch.min(arr))
print(torch.max(arr))
print(torch.mean(arr))



tensor(0.1163, dtype=torch.float64)
tensor(0.9737, dtype=torch.float64)
tensor(0.6683, dtype=torch.float64)


Finding index of a min, max value in a tensor

In [ ]:
print(arr.argmin())
print(arr.argmax())


tensor(3)
tensor(2)


Reshape

In [ ]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9, 1)

x_reshaped, x_reshaped.shape, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[5],
         [5],
         [9],
         [2],
         [7],
         [2],
         [6],
         [9],
         [3]]),
 torch.Size([9, 1]),
 tensor([5, 5, 9, 2, 7, 2, 6, 9, 3]),
 torch.Size([9]))

In [ ]:
# change view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 5, 9, 2, 7, 2, 6, 9, 3]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5, 5, 9, 2, 7, 2, 6, 9, 3]]),
 tensor([[5, 5, 9],
         [2, 7, 2],
         [6, 9, 3]]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x], dim = 0)
x_stacked_1 = torch.stack([x, x, x],  dim = 1)
x_stacked, x_stacked_1


(tensor([[[5, 5, 9],
          [2, 7, 2],
          [6, 9, 3]],
 
         [[5, 5, 9],
          [2, 7, 2],
          [6, 9, 3]],
 
         [[5, 5, 9],
          [2, 7, 2],
          [6, 9, 3]]]),
 tensor([[[5, 5, 9],
          [5, 5, 9],
          [5, 5, 9]],
 
         [[2, 7, 2],
          [2, 7, 2],
          [2, 7, 2]],
 
         [[6, 9, 3],
          [6, 9, 3],
          [6, 9, 3]]]))

In [ ]:
sq_sh = x_reshaped.squeeze().shape 
sq = x_reshaped.squeeze()
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

# After removal of extra dimensions

print(f"\nNew tensor: {sq}")
print(f"New tensor shape: {sq_sh}")

Previous tensor: tensor([[5],
        [5],
        [9],
        [2],
        [7],
        [2],
        [6],
        [9],
        [3]])
Previous tensor shape: torch.Size([9, 1])

New tensor: tensor([5, 5, 9, 2, 7, 2, 6, 9, 3])
New tensor shape: torch.Size([9])


In [ ]:
# torch.unsqueeze( -adds a single dimension to a target tensor at a specific dimension
print(f"Previous targer: {sq}")
print(f"Previous shape: {sq_sh}")

# Add an extra dimension with unsqueeze
x_unsq = sq.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsq}")
print(f"New shape: {x_unsq.shape}")

Previous targer: tensor([5, 5, 9, 2, 7, 2, 6, 9, 3])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 5, 9, 2, 7, 2, 6, 9, 3]])
New shape: torch.Size([1, 9])


In [ ]:
#  torch.permute: rearranges the dimensions of a target tensor in a specified order
x_org = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_perm = x_org.permute(2, 0, 1) # shifts axis of x_org, 0 --> 1, 1 --> 2, 2 --> 0

print(f"Previous shape: {x_org.shape}")
print(f"New shape: {x_perm.shape}") #[colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_org[0, 0, 0] = torch.randint(1, 20000000, (1,1))

x_perm[0,0,0]

#torch.randint(1, 20000000, (1,1)) 


tensor(10472507.)

## Indexing(selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.


In [ ]:
# create a tensor 
import torch
x = torch.arange(1,28).reshape(3,3,3)
x, x.shape


(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

In [ ]:
# Index on our new tensor
x[0]

# Index on the middle bracket
x[0,0]

# Index on the most inner bracket
x[1,2,1]

tensor(17)

# Pytorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -->     `torch.from_numpy(ndarray)`
* PyTorch tensor -->NumPy --> `torch.Tensor.numpy()`


In [ ]:
# NumPy arrat to tensor
import torch
import numpy as np


array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy --> pyTorch, pyTorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

array.dtype, tensor.dtype

torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # pyTorch's dtype is float32

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how aneural network learns:
`Start with random numbers -> tensor operations -> update random numbers to try and make them a better representation of the data -> again -> again -> again...`

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what ranadom seed does, is "flavour" the reandomness. 

In [ ]:
rand_tens_A = torch.rand(3, 4)
rand_tens_B= torch.rand(3, 4)

print(rand_tens_A, "\n", rand_tens_B)
print(rand_tens_A == rand_tens_B)


tensor([[0.5933, 0.6678, 0.0807, 0.4737],
        [0.8228, 0.0409, 0.5550, 0.0069],
        [0.4758, 0.0205, 0.1723, 0.7534]]) 
 tensor([[0.3761, 0.1471, 0.2359, 0.5344],
        [0.8523, 0.4309, 0.9870, 0.9978],
        [0.8331, 0.8291, 0.4428, 0.0850]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed

rand_seed = 45

torch.manual_seed(rand_seed)
rand_tens_C = torch.rand(3,4)

torch.manual_seed(rand_seed)
rand_tens_D = torch.rand(3, 4)
 
print(rand_tens_C)
print(rand_tens_D)
print(rand_tens_C == rand_tens_D)

tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])
tensor([[0.1869, 0.9613, 0.6834, 0.8988],
        [0.0505, 0.5555, 0.7861, 0.0566],
        [0.7842, 0.1480, 0.0388, 0.1037]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Check if PyTorch is accessing GPU

In [ ]:
import torch
torch.cuda.is_available()

True

# Setup Device agnostic code

In [ ]:
if torch.cuda.is_available() == 1:
    device = 'cuda'
else:
    device = 'cpu'
device        

'cuda'

Putting Tensor to GPU

In [ ]:
tensors = torch.tensor([1, 2, 3]) #on CPU (default)
print(tensors, tensors.device)


tensor([1, 2, 3]) cpu


In [ ]:
tens_on_gpu = tensors.to(device)
tens_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Moving tensors to NumPy

In [37]:
tensor_back_on_cpu = tens_on_gpu.cpu().numpy()

tensor_back_on_cpu 

array([1, 2, 3], dtype=int64)