Shape errors:
The inner dimensions must match. Like-----> [3, 2] and [2, 3] 

Multiplications cannot be executed if [a, b] and [a, b].

In [11]:
import numpy as np
import torch

a = torch.tensor([[1, 3], [4, 6]])
b = torch.tensor([[2, 7], [9, 1]])

c = torch.matmul(a, b)

c

tensor([[29, 10],
        [62, 34]])

In [12]:
x =  torch.tensor([[1, 5, 9],
                  [2, 7, 2],
                  [6, 9, 3]])
y = torch.tensor([[1, 3, 77],
                 [2, 5, 78]])

z = torch.matmul(x, y)

z

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x3)

To solve this issue we can use the **transpose** of the matrix. Using transpose method we can manipulate the **shape** of the matrix.


In [13]:
Y = y.T

mulT = torch.matmul(x, Y)
mulT

tensor([[709, 729],
        [177, 195],
        [264, 291]])

Finding sum, mean, max etc using *rand* values

In [14]:
import numpy as np
arr1 = np.random.rand(7)
arr = torch.tensor(arr1)
print(torch.min(arr))
print(torch.max(arr))
print(torch.mean(arr))



tensor(0.1403, dtype=torch.float64)
tensor(0.8740, dtype=torch.float64)
tensor(0.4756, dtype=torch.float64)


Finding index of a min, max value in a tensor

In [15]:
print(arr.argmin())
print(arr.argmax())


tensor(6)
tensor(0)


Reshape

In [32]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [48]:
x_reshaped = x.reshape(9, 1)

x_reshaped, x_reshaped.shape, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]))

In [18]:
# change view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [19]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [20]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x], dim = 0)
x_stacked_1 = torch.stack([x, x, x],  dim = 1)
x_stacked, x_stacked_1


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[5, 5, 5],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [8, 8, 8],
         [9, 9, 9]]))

In [52]:
sq_sh = x_reshaped.squeeze().shape 
sq = x_reshaped.squeeze()
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

# After removal of extra dimensions

print(f"\nNew tensor: {sq}")
print(f"New tensor shape: {sq_sh}")

Previous tensor: tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Previous tensor shape: torch.Size([9, 1])

New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New tensor shape: torch.Size([9])


In [62]:
# torch.unsqueeze( -adds a single dimension to a target tensor at a specific dimension
print(f"Previous targer: {sq}")
print(f"Previous shape: {sq_sh}")

# Add an extra dimension with unsqueeze
x_unsq = sq.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsq}")
print(f"New shape: {x_unsq.shape}")

Previous targer: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])
